services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - ENV_VAR=example

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./frontend/sitio:/usr/share/nginx/html
    depends_on:
      - backend